global:
  domain: null
  imagePullSecret: {}
srv:
  bindings:
    auth:
      serviceInstanceName: xsuaa
  image:
    repository: <your-container-registry>/cpapp-srv
    tag: latest
  resources:
    limits:
      ephemeral-storage: 1G
      memory: 500M
    requests:
      ephemeral-storage: 1G
      cpu: 500m
      memory: 500M
  health_check:
    liveness:
      path: /
    readiness:
      path: /
xsuaa:
  serviceOfferingName: xsuaa
  servicePlanName: application
  parameters:
    xsappname: cpapp
  config: xs-security.json
